### ISSUE TITLE
Ally -> sidekick?

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2016-EvoStar#3]
Discuss @fergunet @raiben

**Comment by fergunet** [comment]
I think "Ally != sidekick". A sidekick is Robin, and an ally is Jim Gordon ;)

Also, I suppose that those names were defined by Campbell in his book, it isn't?

**Comment by JJ** [comment]
But I like Robin!

**Comment by fergunet** [comment]
Also does Barbara Gordon ;)

**Comment by rhgarcia** [comment]
Hi,
Exactly, "Ally" is how Vogler calls it. Following "The writer's journey", an Ally can serve a variety of necessary functions, such as companion, sparring partner, conscience or comic relief. A sidekick ("someone you keep as close to you as your side pocket") is usually an ally (sometimes can play other roles like trickster), but the hero can have allies that are not sidekicks (for example, someone who helps them in a given moment). Vogler mentions the 'sidekick' when talking about classical western allies, for example.
